spring:
  main:
    web-application-type: none
  shell:
    interactive:
      enabled: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: anthropic/claude-3-haiku-20240307
## disable/enable console logging
logging:
  console:

  ## log debug from a cli
  # file:
  #   name: shell.log
  # level:
  #   root: DEBUG
  #   org:
  #     springframework:
  #       cli: DEBUG
  #       shell: DEBUG
